### ISSUE TITLE
Use [fast] instead of [free]

### ISSUE THREAD

**Issue by fspoettel** [matteopic/arkham-editor#1]
Hello, thank you for this useful tool. I'm using this for preparing card data for the [json data repo](https://github.com/kamalisk/arkhamdb-json-data). For the card database, `[fast]` is preferred over `[free]` to signal a lightning action. It would be great if this could be reflected in the tool.

I have this change (and another small json data preference) implemented in my fork if you wish to pull it: https://github.com/matteopic/arkham-editor/compare/main...fspoettel:arkham-editor:main

**Comment by matteopic** [comment]
May I ask you where you found to prefer `[fast]` over `[free]`?
I have just tried a simple search... [free] is used on 856 files, [fast] on 364.
And why remove the sobstitution of three single dot with the specific character?

If there are any guidelines I haven't seen, I'd like to see them.

**Comment by fspoettel** [comment]
@matteopic This is feedback that was mentioned to me directly by the main maintainer on a couple of PRs. I don't think there is a thorough style guide that lives anywhere. I'll link the comments to you here:

- https://github.com/zzorba/arkhamdb-json-data/pull/9#discussion_r1652960538 - fast -> free
- https://github.com/zzorba/arkhamdb-json-data/pull/9#discussion_r1652977392 -> em -> en dash
- https://github.com/zzorba/arkhamdb-json-data/pull/9#discussion_r1652907106 - regarding cite.

The ... I can't find anymore, but in the same line as preferring en over em dashes.

>  I have just tried a simple search... [free] is used on 856 files, [fast] on 364.

Does this include translations? We are currently preparing a cleanup to at least get the english data in line, most of the `[free]` is in old data.

**Comment by matteopic** [comment]
Merged

**Comment by fspoettel** [comment]
awesome, thank you! 👍
